// Generated by gencpp from file meccanum_kinematics/microlidar.msg
// DO NOT EDIT!


#ifndef MECCANUM_KINEMATICS_MESSAGE_MICROLIDAR_H
#define MECCANUM_KINEMATICS_MESSAGE_MICROLIDAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace meccanum_kinematics
{
template <class ContainerAllocator>
struct microlidar_
{
  typedef microlidar_<ContainerAllocator> Type;

  microlidar_()
    : frontsensor(0.0)
    , rightsensor(0.0)
    , leftsensor(0.0)
    , rearsensor(0.0)  {
    }
  microlidar_(const ContainerAllocator& _alloc)
    : frontsensor(0.0)
    , rightsensor(0.0)
    , leftsensor(0.0)
    , rearsensor(0.0)  {
  (void)_alloc;
    }



   typedef float _frontsensor_type;
  _frontsensor_type frontsensor;

   typedef float _rightsensor_type;
  _rightsensor_type rightsensor;

   typedef float _leftsensor_type;
  _leftsensor_type leftsensor;

   typedef float _rearsensor_type;
  _rearsensor_type rearsensor;





  typedef boost::shared_ptr< ::meccanum_kinematics::microlidar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::meccanum_kinematics::microlidar_<ContainerAllocator> const> ConstPtr;

}; // struct microlidar_

typedef ::meccanum_kinematics::microlidar_<std::allocator<void> > microlidar;

typedef boost::shared_ptr< ::meccanum_kinematics::microlidar > microlidarPtr;
typedef boost::shared_ptr< ::meccanum_kinematics::microlidar const> microlidarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::meccanum_kinematics::microlidar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::meccanum_kinematics::microlidar_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace meccanum_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'meccanum_kinematics': ['/home/pi/catkin_ws/src/meccanum_kinematics/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meccanum_kinematics::microlidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meccanum_kinematics::microlidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meccanum_kinematics::microlidar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "287772e6e21dd828d901a49ff2d341a9";
  }

  static const char* value(const ::meccanum_kinematics::microlidar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x287772e6e21dd828ULL;
  static const uint64_t static_value2 = 0xd901a49ff2d341a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "meccanum_kinematics/microlidar";
  }

  static const char* value(const ::meccanum_kinematics::microlidar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 frontsensor\n\
float32 rightsensor\n\
float32 leftsensor\n\
float32 rearsensor\n\
\n\
";
  }

  static const char* value(const ::meccanum_kinematics::microlidar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontsensor);
      stream.next(m.rightsensor);
      stream.next(m.leftsensor);
      stream.next(m.rearsensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct microlidar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::meccanum_kinematics::microlidar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::meccanum_kinematics::microlidar_<ContainerAllocator>& v)
  {
    s << indent << "frontsensor: ";
    Printer<float>::stream(s, indent + "  ", v.frontsensor);
    s << indent << "rightsensor: ";
    Printer<float>::stream(s, indent + "  ", v.rightsensor);
    s << indent << "leftsensor: ";
    Printer<float>::stream(s, indent + "  ", v.leftsensor);
    s << indent << "rearsensor: ";
    Printer<float>::stream(s, indent + "  ", v.rearsensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MECCANUM_KINEMATICS_MESSAGE_MICROLIDAR_H
