// Generated by gencpp from file meccanum_kinematics/speed.msg
// DO NOT EDIT!


#ifndef MECCANUM_KINEMATICS_MESSAGE_SPEED_H
#define MECCANUM_KINEMATICS_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace meccanum_kinematics
{
template <class ContainerAllocator>
struct speed_
{
  typedef speed_<ContainerAllocator> Type;

  speed_()
    : frontleft(0.0)
    , frontright(0.0)
    , rearleft(0.0)
    , rearright(0.0)  {
    }
  speed_(const ContainerAllocator& _alloc)
    : frontleft(0.0)
    , frontright(0.0)
    , rearleft(0.0)
    , rearright(0.0)  {
  (void)_alloc;
    }



   typedef float _frontleft_type;
  _frontleft_type frontleft;

   typedef float _frontright_type;
  _frontright_type frontright;

   typedef float _rearleft_type;
  _rearleft_type rearleft;

   typedef float _rearright_type;
  _rearright_type rearright;





  typedef boost::shared_ptr< ::meccanum_kinematics::speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::meccanum_kinematics::speed_<ContainerAllocator> const> ConstPtr;

}; // struct speed_

typedef ::meccanum_kinematics::speed_<std::allocator<void> > speed;

typedef boost::shared_ptr< ::meccanum_kinematics::speed > speedPtr;
typedef boost::shared_ptr< ::meccanum_kinematics::speed const> speedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::meccanum_kinematics::speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::meccanum_kinematics::speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace meccanum_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'meccanum_kinematics': ['/home/pi/catkin_ws/src/meccanum_kinematics/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::meccanum_kinematics::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meccanum_kinematics::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meccanum_kinematics::speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meccanum_kinematics::speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meccanum_kinematics::speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meccanum_kinematics::speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::meccanum_kinematics::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ed2399f8b7a18e0ff91e51b61462098";
  }

  static const char* value(const ::meccanum_kinematics::speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ed2399f8b7a18e0ULL;
  static const uint64_t static_value2 = 0xff91e51b61462098ULL;
};

template<class ContainerAllocator>
struct DataType< ::meccanum_kinematics::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "meccanum_kinematics/speed";
  }

  static const char* value(const ::meccanum_kinematics::speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::meccanum_kinematics::speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 frontleft\n\
float32 frontright\n\
float32 rearleft\n\
float32 rearright\n\
";
  }

  static const char* value(const ::meccanum_kinematics::speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::meccanum_kinematics::speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontleft);
      stream.next(m.frontright);
      stream.next(m.rearleft);
      stream.next(m.rearright);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::meccanum_kinematics::speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::meccanum_kinematics::speed_<ContainerAllocator>& v)
  {
    s << indent << "frontleft: ";
    Printer<float>::stream(s, indent + "  ", v.frontleft);
    s << indent << "frontright: ";
    Printer<float>::stream(s, indent + "  ", v.frontright);
    s << indent << "rearleft: ";
    Printer<float>::stream(s, indent + "  ", v.rearleft);
    s << indent << "rearright: ";
    Printer<float>::stream(s, indent + "  ", v.rearright);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MECCANUM_KINEMATICS_MESSAGE_SPEED_H
